title: Sarah Wallace Portfolio
theme: jekyll-theme-minimal

navigation:
  - title: "About"
    url: "/"
  - title: "Project Write-Ups"
    url: "/project-write-ups"
  - title: "Education"
    url: "/education"
  - title: "Contact"
    url: "mailto:youremail@example.com"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/sarah-w-15205226"
  - title: "GitHub"
    url: "https://github.com/Swall1545"
  - title: "GitLab"
    url: "https://gitlab.com/swall15"
  - title: "Handshake"
    url: "https://wgu.joinhandshake.com/profiles/h5vxsj"
